from pathlib import Path
from typing import Tuple
from .models import CompilationArtifact

class ArtifactDiscoverer:
    """Discovers output artifacts generated by the compiler."""
    
    @staticmethod
    def collect(root: Path, main_file: str) -> Tuple[CompilationArtifact, ...]:
        artifacts = []
        stem = Path(main_file).stem
        
        extensions_to_types = {
            ".pdf": "pdf",
            ".log": "log",
            ".aux": "aux",
            ".out": "out",
            ".toc": "toc",
            ".bbl": "bbl",
            ".blg": "blg"
        }
        
        for ext, art_type in extensions_to_types.items():
            path = root / f"{stem}{ext}"
            if path.exists() and path.is_file():
                artifacts.append(CompilationArtifact(
                    artifact_type=art_type,
                    path=path
                ))
                
        return tuple(artifacts)
