from typing import Protocol, Any, Dict, Optional, List, runtime_checkable

@runtime_checkable
class ILLMGateway(Protocol):
    """Abstraction for LLM provider access. Agents never call LLMs directly."""
    def complete(self, prompt: str, context: Optional[Dict[str, Any]] = None) -> str: ...

@runtime_checkable
class IMemoryGateway(Protocol):
    """Abstraction for memory/knowledge retrieval. Agents never access storage directly."""
    def search(self, query: str, top_k: int = 5) -> List[Dict[str, Any]]: ...
    def store(self, content: str, metadata: Optional[Dict[str, Any]] = None) -> None: ...

@runtime_checkable
class IAgent(Protocol):
    """The mandatory contract every Thesis Intelligence agent must implement."""
    
    @property
    def role(self) -> str: ...
    
    def handle_event(self, event_name: str, payload: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def handle_message(self, sender_role: str, payload: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...

@runtime_checkable
class IAgentContext(Protocol):
    """The restricted OS sandbox provided to every agent. No agent touches the OS directly."""
    def submit_build(self, target_dir: str, main_file: str = "main.tex", priority: int = 10) -> str: ...
    def query_memory(self, query: str, top_k: int = 5) -> List[Dict[str, Any]]: ...
    def complete_llm(self, prompt: str, context: Optional[Dict[str, Any]] = None) -> str: ...
    def send_message(self, target_role: str, payload: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def read_thesis_file(self, relative_path: str) -> str: ...
    def write_thesis_file(self, relative_path: str, content: str) -> None: ...
